In [30]:
import numpy as np
a=np.arange(30).reshape(2,3,5)
print a

N = a.shape[0]
input_shape = a.shape[1:]
D=np.prod(input_shape)


b=np.reshape(a,(N,D))
c=np.reshape(b,a.shape)
print c.shape

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
(2, 3, 5)


In [13]:
x=np.array([[2,4,5],[4,4,5]])
y=np.array([4,5,6])
z=(x,y)
print z[0][0][0]


2


In [17]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [25]:
y=[2,4]
print len(y)

2


In [44]:
d={}
for i in range(len(y)):
    d['w'+str(i)]=i if i==0 else i+1
    
print d
    

{'w1': 2, 'w0': 0}


In [51]:
L2=[i**2 for i in range(3)]
print np.sum(L2)

5
