In [4]:
import numpy as np
a=np.arange(30).reshape(2,3,5)
print a.shape
print a[:,0,:]

print a.max()
dd= np.where(a==a.max())

print a[dd]
np.unravel_index(a.argmax(),a.shape)


N = a.shape[0]
input_shape = a.shape[1:]
D=np.prod(input_shape)


b=np.reshape(a,(N,D))
c=np.reshape(b,a.shape)
print c.shape

(2, 3, 5)
[[ 0  1  2  3  4]
 [15 16 17 18 19]]
29
[29]
(2, 3, 5)


In [ ]:
x=np.array([[2,4,5],[4,4,5]])
y=np.array([4,5,6])
z=(x,y)
print z[0][0][0]


In [ ]:
np.zeros(5)

In [ ]:
y=[2,4]
print len(y)

In [ ]:
d={}
for i in range(len(y)):
    d['w'+str(i)]=i if i==0 else i+1
    
print d
    

In [ ]:
L2=[i**2 for i in range(3)]
print np.sum(L2)

In [ ]:
for i in range(3-1,-1,-1):
    print i

In [ ]:
 10 ** uniform(-6, 1)

In [ ]:
H=np.random.rand(2,2) < 0.3
print H

In [ ]:
U=np.array(([2,1],[2,3]))
print U

In [ ]:
U*H

In [27]:
ss=np.array(([1,3],[2,4,],[2,3]))
bb=np.array([1,3])

print ss+bb

print np.rot90(ss, 1)

print np.empty_like(bb)
print np.zeros(ss.shape)


[[2 6]
 [3 7]
 [3 6]]
[[3 4 3]
 [1 2 2]]
[1 3]
[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]


In [7]:
a = np.ones((10,3,3,2))
npad = ((0,0),(0,0), (1,2), (2,1))

b = np.pad(a, pad_width=npad, mode='constant', constant_values=0)
print b

[[[[ 0.  0.  0.  0.  0.]
   [ 0.  0.  1.  1.  0.]
   [ 0.  0.  1.  1.  0.]
   [ 0.  0.  1.  1.  0.]
   [ 0.  0.  0.  0.  0.]
   [ 0.  0.  0.  0.  0.]]

  [[ 0.  0.  0.  0.  0.]
   [ 0.  0.  1.  1.  0.]
   [ 0.  0.  1.  1.  0.]
   [ 0.  0.  1.  1.  0.]
   [ 0.  0.  0.  0.  0.]
   [ 0.  0.  0.  0.  0.]]

  [[ 0.  0.  0.  0.  0.]
   [ 0.  0.  1.  1.  0.]
   [ 0.  0.  1.  1.  0.]
   [ 0.  0.  1.  1.  0.]
   [ 0.  0.  0.  0.  0.]
   [ 0.  0.  0.  0.  0.]]]


 [[[ 0.  0.  0.  0.  0.]
   [ 0.  0.  1.  1.  0.]
   [ 0.  0.  1.  1.  0.]
   [ 0.  0.  1.  1.  0.]
   [ 0.  0.  0.  0.  0.]
   [ 0.  0.  0.  0.  0.]]

  [[ 0.  0.  0.  0.  0.]
   [ 0.  0.  1.  1.  0.]
   [ 0.  0.  1.  1.  0.]
   [ 0.  0.  1.  1.  0.]
   [ 0.  0.  0.  0.  0.]
   [ 0.  0.  0.  0.  0.]]

  [[ 0.  0.  0.  0.  0.]
   [ 0.  0.  1.  1.  0.]
   [ 0.  0.  1.  1.  0.]
   [ 0.  0.  1.  1.  0.]
   [ 0.  0.  0.  0.  0.]
   [ 0.  0.  0.  0.  0.]]]


 [[[ 0.  0.  0.  0.  0.]
   [ 0.  0.  1.  1.  0.]
   [ 0.  0.  1.  1.  0.]
   [ 0.  

In [8]:
ff=None
ff[1]=2

TypeError: 'NoneType' object does not support item assignment

In [20]:
s=np.zeros(([3,2,2,3],))
s[1,:,1,2]

array([ 0.,  0.])

NameError: name 'F' is not defined

In [1]:
  for i in range(N):
      for f in range(F):
          for h in range(HH):
                for k in range(WW):
                    for c in range(CC):
                       #dw[f,c, :, : ] += x_pad[i,c,(h*stride):HH+(h*stride),(k*stride):WW+(k*stride)]*
                           dw[f,c, h, k]+=np.sum(x_pad[i,c,(h*stride):H_+(h*stride),(k*stride):W_+(k*stride)]* dout[i,f])
                    
                       #print dw[f,c, h*HH:(h+1)*HH, k*WW:(k+1)*WW].shape
                       #print x_pad[i,c,(h*stride):HH+(h*stride),(k*stride):WW+(k*stride)].shape 

NameError: name 'N' is not defined

In [1]:
  for i in range(N):
      for f in range(F):
          for c in range(CC):
              for h in range(HH):
                  for k in range(WW):             
                      dw[f,c, h, k]+=np.sum(dout_pad[i,f,(h*stride):H+(h*stride),(k*stride):W+(k*stride)]* x_r[i,c])

NameError: name 'N' is not defined

In [2]:
  for i in range(N):
      for f in range(F):
          for c in range(CC):
              for h in range(HH):
                  for k in range(WW):             
                      dw[f,c, h, k]+=np.sum(x_pad[i,c,(h*stride):H+(h*stride),(k*stride):W+(k*stride)]* dout_r[i,f]) 

NameError: name 'N' is not defined

In [23]:
a=np.array(([2,4,6,7,4,2,4,6,7,8],[1,2,3,4,5,6,7,8,9,19],[3,2,1,5,5,6,7,8,9,19]))
print a
st=2
for h in range(a.shape[0]):
    for w in range(a.shape[1]):
        print a[h:h+2*st:st,w:w+2*st:st]
        print 'next'


[[ 2  4  6  7  4  2  4  6  7  8]
 [ 1  2  3  4  5  6  7  8  9 19]
 [ 3  2  1  5  5  6  7  8  9 19]]
[[2 6]
 [3 1]]
next
[[4 7]
 [2 5]]
next
[[6 4]
 [1 5]]
next
[[7 2]
 [5 6]]
next
[[4 4]
 [5 7]]
next
[[2 6]
 [6 8]]
next
[[4 7]
 [7 9]]
next
[[ 6  8]
 [ 8 19]]
next
[[7]
 [9]]
next
[[ 8]
 [19]]
next
[[1 3]]
next
[[2 4]]
next
[[3 5]]
next
[[4 6]]
next
[[5 7]]
next
[[6 8]]
next
[[7 9]]
next
[[ 8 19]]
next
[[9]]
next
[[19]]
next
[[3 1]]
next
[[2 5]]
next
[[1 5]]
next
[[5 6]]
next
[[5 7]]
next
[[6 8]]
next
[[7 9]]
next
[[ 8 19]]
next
[[9]]
next
[[19]]
next


In [24]:
  for i in range(N):
      for f in range(F):
          for c in range(CC):
              for h in range(HH):
                  for k in range(WW):             
                      dw[f,c, h, k]+=np.sum(x_pad[i,c,(h*stride):H_+(h*stride),(k*stride):W_+(k*stride)]* dout[i,f])  

NameError: name 'F' is not defined

In [25]:
  for i in range(N):
    for f in range(F):
        for h in range(H):
            for k in range(W):
                for c in range(C):
                   dx[i,c, h, k]+=np.sum(dout_pad[i,f,h:h+HH*stride:stride,k:k+WW*stride:stride]* w_r[f,c])  

NameError: name 'F' is not defined