In [1]:
import numpy as np
a=np.arange(30).reshape(2,3,5)
print a

N = a.shape[0]
input_shape = a.shape[1:]
D=np.prod(input_shape)


b=np.reshape(a,(N,D))
c=np.reshape(b,a.shape)
print c.shape

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
(2, 3, 5)


In [ ]:
x=np.array([[2,4,5],[4,4,5]])
y=np.array([4,5,6])
z=(x,y)
print z[0][0][0]


In [ ]:
np.zeros(5)

In [ ]:
y=[2,4]
print len(y)

In [ ]:
d={}
for i in range(len(y)):
    d['w'+str(i)]=i if i==0 else i+1
    
print d
    

In [ ]:
L2=[i**2 for i in range(3)]
print np.sum(L2)

In [ ]:
for i in range(3-1,-1,-1):
    print i

In [ ]:
 10 ** uniform(-6, 1)

In [ ]:
H=np.random.rand(2,2) < 0.3
print H

In [ ]:
U=np.array(([2,1],[2,3]))
print U

In [ ]:
U*H

In [4]:
ss=np.array(([1,3],[2,4,],[2,3]))
bb=np.array([1,3])

print ss+bb


[[2 6]
 [3 7]
 [3 6]]


In [7]:
a = np.ones((10,3,3,2))
npad = ((0,0),(0,0), (1,2), (2,1))

b = np.pad(a, pad_width=npad, mode='constant', constant_values=0)
print b

[[[[ 0.  0.  0.  0.  0.]
   [ 0.  0.  1.  1.  0.]
   [ 0.  0.  1.  1.  0.]
   [ 0.  0.  1.  1.  0.]
   [ 0.  0.  0.  0.  0.]
   [ 0.  0.  0.  0.  0.]]

  [[ 0.  0.  0.  0.  0.]
   [ 0.  0.  1.  1.  0.]
   [ 0.  0.  1.  1.  0.]
   [ 0.  0.  1.  1.  0.]
   [ 0.  0.  0.  0.  0.]
   [ 0.  0.  0.  0.  0.]]

  [[ 0.  0.  0.  0.  0.]
   [ 0.  0.  1.  1.  0.]
   [ 0.  0.  1.  1.  0.]
   [ 0.  0.  1.  1.  0.]
   [ 0.  0.  0.  0.  0.]
   [ 0.  0.  0.  0.  0.]]]


 [[[ 0.  0.  0.  0.  0.]
   [ 0.  0.  1.  1.  0.]
   [ 0.  0.  1.  1.  0.]
   [ 0.  0.  1.  1.  0.]
   [ 0.  0.  0.  0.  0.]
   [ 0.  0.  0.  0.  0.]]

  [[ 0.  0.  0.  0.  0.]
   [ 0.  0.  1.  1.  0.]
   [ 0.  0.  1.  1.  0.]
   [ 0.  0.  1.  1.  0.]
   [ 0.  0.  0.  0.  0.]
   [ 0.  0.  0.  0.  0.]]

  [[ 0.  0.  0.  0.  0.]
   [ 0.  0.  1.  1.  0.]
   [ 0.  0.  1.  1.  0.]
   [ 0.  0.  1.  1.  0.]
   [ 0.  0.  0.  0.  0.]
   [ 0.  0.  0.  0.  0.]]]


 [[[ 0.  0.  0.  0.  0.]
   [ 0.  0.  1.  1.  0.]
   [ 0.  0.  1.  1.  0.]
   [ 0.  

In [8]:
ff=None
ff[1]=2

TypeError: 'NoneType' object does not support item assignment

In [20]:
s=np.zeros((3,2,2,3))
s[1,:,1,2]

array([ 0.,  0.])